server:
  port: 10087
spring:
  application:
    name: eureka-server # 应用名称，会在Eureka中作为服务的id标识（serviceId）
eureka:
  client:
    registry-fetch-interval-seconds: 30
    service-url: # EurekaServer的地址，现在是自己的地址，如果是集群，需要写其它Server的地址。
      defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10087/eureka
  server:
    enable-self-preservation: false # 关闭自我保护模式（缺省为打开）
